### ISSUE TITLE
Dual Screen

### ISSUE THREAD

**Issue by jamesoc91** [veyon/veyon#315]
I am exploring Veyon at them moment, I am looking for a solution. I am running a dual screen on the teacher machine and want to only broadcast one display when using the broadcast feature, is this possible?

**Comment by tobydox** [comment]
Welcome to Veyon! Please see http://veyon.readthedocs.io/en/latest/admin/faq.html#how-can-i-view-or-control-all-monitors-of-a-remote-computer for information on how to enable dual screen support for a computer. In your case this needs to be enabled for the master computer so the demo server can access both screens of the master computer.

**Comment by jamesoc91** [comment]
Thank you. I have that already configured, what i want to do is broadcast the secondary monitor from the master only , is there a way to do this or do i need to use an alternative vnc server?

**Comment by tobydox** [comment]
So after enabling dual screen support on the master computer you can still only see the primary monitor on clients in demo mode?

**Comment by jamesoc91** [comment]
I can see both screens, however I dont want my primary monitor to show in the broadcast

**Comment by tobydox** [comment]
I understand - will leave the issue open for discussion and development in the future.

**Comment by JohnKokin** [comment]
And the problem was solved?
I'm also interested in this functionality

**Comment by jcromero** [comment]
I'm also interested in this functionality

**Comment by fnt-cb** [comment]
I would really like this feature. In the current version 4.2.2 it still does not seem to work!

**Comment by tobydox** [comment]
Thanks for your feedback! The feature still has not been implemented as it would require several days of development which I'm not able to carry out for free. We'll have to wait until a company or organization is willing to pay for the development of this feature and/or someone else contributes the required code changes.

**Comment by SixThreeFive7311** [comment]
Installed version 4.3 in a lab with all dual screen workstations: 1 master, 24 clients. The teacher indicated that since the upgrade, he can continue to see both student screens, but now his desktop was showing primary and secondary monitor. He only wants to display the primary monitor from his workstation to all student workstations.

Coming from older Veyon versions 4.0 and 4.1, we had to enable Multi Monitor support post-installation. Maybe now it's on by default? In any case, disabling Multi Monitor support corrected his issue and now he is back to only sharing the primary display and not the secondary. As far as we can tell, Veyon doesn't give you an option of which monitor to share from the master - it's either primary or both.

Used the CLI for this:
`veyon-cli config set UltraVNC/MultiMonitorSupport false`

And then a service restart for good measure:
`veyon-cli service restart`

Teacher reports all is working as it was before the upgrade.

**Comment by tobydox** [comment]
As of Veyon 4.5 you can select which screen to broadcast so I consider this issue as done and closing it.
